# Generated by Django 4.0.4 on 2022-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_line_eight_invoice_line_eight_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 8'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 9'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 7'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 6'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 10'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 2'),
        ),
    ]
